<?php
define("DB_USER","INSERT_YOUR_DB_USERNAME_HERE");
define("DB_PASSWORD","INSERT_YOUR_DB_PASSWORD_HERE");
define("DB_HOST","INSERT_YOUR_DB_HOST_HERE");
define("DB_NAME","INSERT_YOUR_DB_NAME_HERE");
?>